### PR TITLE
Adding Travis-Ci Support For Arm64

### PR DESCRIPTION
**Pull request by ossdev07**
Travis-CI has added support for ARM64. Added ARM64 job in Travis-CI.

### CODE REVIEW

**Comment by ossdev07** [comment]
Ping @g-k can you have a look at this PR.

**Comment by g-k** [comment]
Hi @ossdev07, thanks for the PR! What's the benefit of testing on ARM64? Have you noticed any regressions that only occur on ARM?

AFAIK bleach doesn't have any native dependencies.

**Comment by rhenwood-arm** [comment]
Hi @g-k , I have been working with @ossdev07 on a down-stream project on AArch64 (ARM64) that has bleach as a dependency. As you point out, bleach is a pure python project with a straightforward Travis-CI build job and that doesn't have a binary release. In this case, there is very little benefit in testing on alternative architectures, and this PR can probably be held in reserve until it is needed.

**Comment by g-k** [comment]
Ok thanks! Closing per https://github.com/mozilla/bleach/pull/506#issuecomment-585419723 we would like to know about architecture specific regressions, but will rely on downstream consumers to report them.

**Pull request closed without merging**
