### PR TITLE
Add extra_serializer_options to the clean and linkify params

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by willkg** [comment]
@jespino I know it's been *ages* since you worked on this, but is it possible for you to fix the merge conflicts? If not, I can take this over and finish it up.

**Comment by jespino** [comment]
Hi, I can take a look to it, thanks

**Comment by jespino** [comment]
Now is up to date, but with the initial approach of extra argument to functions (I understand is the less intrusive option to not break backward compatibility). Thanks for take the time to review it :smile:

**Comment by jespino** [comment]
Any news about it?

**Comment by willkg** [comment]
I screwed up. I didn't spend enough time looking into the context here before asking you to fix merge conflicts.

I just went through everything involved. The issue in #129 is specifically "attribute ordering isn't stable between bleach calls" and generalized into the solution "if only we could pass in additional serializer arguments so we could fix that problem". @jsocol in an earlier comment was pretty concerned about how this solution opens up a huge leaky hole in the API that creates a bunch of problems for us. For a contrived example, if bleach ever were to switch HTML libs, this API change could cause a lot of heartache for users.

Anyhow, the attribute ordering problem is also covered in #121 which was fixed in https://github.com/mozilla/bleach/commit/2df578fdb7d3428cbcbfa578805a2173435d4cca in December 2014. That's available now.

Thus the specific problem that is the crux of #129 seems like a duplicate of #121 and that's fixed so I spent some time looking for other compelling use cases that would require some kind of way to set additional serializer arguments. I don't see evidence of others presently.

Given that, I think I want to push off this kind of change until we have a compelling use case.

Thank you for writing up the issue and working on it! I apologize for screwing up earlier.

Closing this out.

**Pull request closed without merging**
