### PR TITLE
Correct dublicates in email_re

### PR DESCRIPTION
**Pull request by tonal**
see #247

### CODE REVIEW

**Comment by willkg** [comment]
Can you add tests for this that show the problem and that these changes fixed it?

**Comment by tonal** [comment]
```python
incorrect_email = '"\\\015"@opa.ru'
email_re.match(incorrect_email)
```

**Comment by willkg** [comment]
Between when you did this and now, I rewrote linkify. I took these commits and reapplied them to the new code and put that in #264.

Closing this in favor of that.

**Comment by willkg** [comment]
Thank you for fixing this!

**Pull request closed without merging**
