### PR TITLE
add test website and scripts

### PR DESCRIPTION
**Pull request by g-k**
refs: https://github.com/mozilla/bleach/issues/242 https://github.com/mozilla-services/foxsec/issues/133

This probably shouldn't go in as it stands, but I thought I'd document my changes here.

The test page was initially copied from https://cure53.de/purify (dual MPL 2 and Apache licensed which should be compatible) and requires some attribution.

glorious web 1.0 styles:

screen shot 2017-02-22 at 7 41 58 pm

### CODE REVIEW

**Comment by willkg** [comment]
This looks really interesting and I <3 how this builds a framework we can reuse going forward. I have a few thoughts on this.

It'd be good to be able to verify that the test harness is working by using one of those test cases without passing it through `bleach.clean` and having it do a JS alert or something like that. Maybe have an additional button that does what the `onload` event listener is doing, except not running it through `bleach.clean`?

Can we say with 100% confidence that running all the tests through `bleach.clean` and concatenating the output and displaying that is equivalent to displaying them one at a time? In other words, by concatenating them, do we inadvertently reduce the efficacy of the test?

**Comment by g-k** [comment]
> Maybe have an additional button that does what the onload event listener is doing, except not running it through bleach.clean?

+1  I tried this by commenting out the code a button to do it would be better.  

> Can we say with 100% confidence that running all the tests through bleach.clean and concatenating the output and displaying that is equivalent to displaying them one at a time? 

No, that's just an artifact of the page I pulled in. I could see dangling markup vectors might somehow canceling each other out.

> In other words, by concatenating them, do we inadvertently reduce the efficacy of the test?

Yes.

Improvements TODO:

- [ ] button to pass a testcase through without cleaning
- [ ] testcase isolation: create one iframe per testcase or iterate through sending them to one iframe
- [ ] add an endpoint for testing linkify?

Also, instead of manually validating each testcase, I was thinking we could instrument the page to check things like window.alert is called on the dirty output and not called on the bleached output.

**Comment by willkg** [comment]
I haven't wrapped my head around linkify, yet, so I don't know what the deal is there. With `clean`, we're making security-related promises about the output. I'm not sure we're doing the same with `linkify`. But maybe we are?

**Comment by g-k** [comment]
The linkify docs say there's some sanitization, but I'm not sure how that's implemented.

> By default, linkify() will perform some sanitization, only allowing a set of “safe” tags.

Going to punt on that for now.

**Comment by willkg** [comment]
I'll look at linkify next week. Maybe it's due for an overhaul especially if we're making safety promises. Part of me wonders if it's doing sanitization, whether we should just make it a flag for clean. It's probably just a Filter at this point.

**Comment by willkg** [comment]
@g-k Is this waiting on anything or is it ready to get reviewed again?

**Comment by g-k** [comment]
It's ready to be reviewed again.

**Comment by willkg** [comment]
Ok! Sorry about that. I didn't mean to let this sit for so long.

I'll look through it some time this week again and land it.

**Comment by g-k** [comment]
No problem! I'm open to other approaches like putting it in a different
library or closing this in favor of something else too.

**Comment by willkg** [comment]
I think this looks good. Thank you!

**Pull request merged**
