### PR TITLE
Auto-release to PyPI on tag. Fix #209.

### LINKED ISSUE #209: set up auto-push-to-pypi via travis
Jazzband and other projects have a setup where you tag the code, it gets tested by travis and then that gets pushed to pypi.

We should do that for bleach, too. Then we don't have to worry about everyone having admin access on pypi.

### PR DESCRIPTION
**Pull request by jezdez**
This also makes wheel files be universal (Python 2 & 3).

### CODE REVIEW

**Comment by jezdez** [comment]
@willkg r?

**Comment by willkg** [comment]
Looks good to me! Thank you for doing this!

**Comment by jezdez** [comment]
@willkg No problem, let me know if you see any oddities. In case you want to use your own username, you can install the Travis client and run `echo "your-password" | travis encrypt --add deploy.password`

**Comment by jezdez** [comment]
Oh and change the `username` field, obviously :)

**Comment by willkg** [comment]
Will do!

**Pull request merged**
