### PR TITLE
Add Mozilla Code of Conduct

### LINKED ISSUE #440: CODE_OF_CONDUCT.md file missing
As of January 1 2019, Mozilla requires that all GitHub projects include this [CODE_OF_CONDUCT.md](https://github.com/mozilla/repo-templates/blob/master/templates/CODE_OF_CONDUCT.md) file in the project root. The file has two parts:

1. Required Text - All text under the headings *Community Participation Guidelines and How to Report*, are required, and should not be altered.
2. Optional Text - The Project Specific Etiquette heading provides a space to speak more specifically about ways people can work effectively and inclusively together. Some examples of those can be found on the [Firefox Debugger](https://github.com/devtools-html/debugger.html/blob/master/CODE_OF_CONDUCT.md) project, and [Common Voice](https://github.com/mozilla/voice-web/blob/master/CODE_OF_CONDUCT.md). (The optional part is commented out in the [raw template file](https://raw.githubusercontent.com/mozilla/repo-templates/blob/master/templates/CODE_OF_CONDUCT.md), and will not be visible until you modify and uncomment that part.)

If you have any questions about this file, or Code of Conduct policies and procedures, please reach out to Mozilla-GitHub-Standards+CoC@mozilla.com.

_(Message COC001)_

### PR DESCRIPTION
**Pull request by Mozilla-GitHub-Standards**
Fixes #440

_(Message COC002)_

### CODE REVIEW

**Comment by g-k** [comment]
We already have a CoC section in the readme at https://github.com/mozilla/bleach#code-of-conduct and a top-level CoC.rst https://github.com/mozilla/bleach/blob/master/CODE_OF_CONDUCT.rst

We might need to update those with the language from this PR.

@hwine will the bot pick up the `.rst` CoC file? And is `.rst` version of the CoC available?

**Comment by hwine** [comment]
At the moment, ``.rst`` files are not spotted, but others have asked the same thing.

Updating the language, and having it at the top, appear to be the key requests. At the least, ensure the html links are the same.

**Comment by hwine** [comment]
Actually, it must be a *.md for it to integrate with GitHub's workflow properly. an *.rst does not show up in the "community insight" section.

**Comment by willkg** [comment]
I'm having a related conversation about this here: https://github.com/mozilla-services/socorro/pull/4864

**Comment by Mozilla-GitHub-Standards** [comment]
I feel like there is an understanding now, on why .md is the standard, 
please let me know if there are any additional concerns I can help with.

**Comment by g-k** [comment]
Thanks willkg! I commented there.

**Comment by g-k** [comment]
OK I'm going to land this and I'll open an issue for making this work per Will's blog post https://bluesock.org/~willkg/blog/mozilla/code_of_conduct.html

**Pull request merged**
