### PR TITLE
Sync travis and tox environments

### PR DESCRIPTION
**Pull request by willkg**
This makes sure travis and tox are testing Bleach with the same
configurations.

### CODE REVIEW

**Comment by willkg** [comment]
@g-k When you get a chance, can you look this over?

**Comment by willkg** [comment]
As a side note, there are some travis-tox integration libs out there, but this doesn't use one of them because I don't have any experience with them and didn't want to spend time looking into them right now. If someone else had experience with one of them and wanted to do a PR to set it up, that'd be super sweet.

**Comment by willkg** [comment]
Thank you!

**Comment by g-k** [comment]
Yeah, I don't see the configs changing frequently enough to warrant pulling in another library.

**Pull request merged**
