### PR TITLE
Do not add trailing period when email address is at the end of a sentence

### PR DESCRIPTION
**Pull request by znerol**

### CODE REVIEW

**Comment by willkg** [comment]
I added this to the v1.5 milestone and will work through it next week.

**Comment by znerol** [comment]
What about the failing 2.6 test? Is that related to the changes here?

**Comment by aRkadeFR** [comment]
@znerol : your travis job on py2.6 failed because of flake8 (https://travis-ci.org/mozilla/bleach/jobs/158673872) . This is not related to the changes, but because of the latest version of flake8 which doesn't support py2.6 anymore (https://gitlab.com/pycqa/flake8/issues/187). I open the discussion on a possible solution on my PR (https://github.com/mozilla/bleach/pull/220#issuecomment-251941044).

**Comment by willkg** [comment]
I pushed a py.test rewrite and broke the test in this PR. I fixed it in PR #228. I'm going to close this PR for that one.

**Pull request closed without merging**
